---
include:
  - board: nice_nano_v2
    shield: charybdis_left
    cmake-args: -DZEPHYR_MODULES=../../modules/threshold_module -DDTS_ROOT=/__w/CharybdisMK2/CharybdisMK2/modules/threshold_module

  - board: nice_nano_v2
    shield: charybdis_right
    cmake-args: -DZEPHYR_MODULES=../../modules/threshold_module -DDTS_ROOT=/__w/CharybdisMK2/CharybdisMK2/modules/threshold_module

  - board: nice_nano_v2
    shield: settings_reset
